# Generated by Django 4.2.7 on 2023-11-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='encryption_key',
            field=models.BinaryField(default=b'default'),
        ),
    ]
