# Generated by Django 4.2.7 on 2023-11-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_userfile_encryption_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='encryption_key',
            field=models.BinaryField(),
        ),
    ]
