# Generated by Django 4.2.7 on 2023-11-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_userfile_encryption_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
